# -------------
# Gitpod config
# -------------
ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: pnpm i
    command: |
      export HMR_HOST=`gp url 3000`
      pnpm run dev
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - svelte.svelte-vscode
    - fivethree.vscode-svelte-snippets